### ISSUE TITLE
Absolute positioning and top

### ISSUE THREAD

**Issue by jim-rosales** [benfin28/prj-rev-bwfs-tea-cozy#4]
For this section as mentioned in issue #3 it's best to avoid top along with absolute positioning. For example in the gist provided in #3 the CSS you could have used for the container is:

```CSS
/* Store Section */

.flex-container {
  display: flex;
  justify-content: center;
  flex-wrap: wrap;
}

/* Store Section */

#store {
  width: 1000px;
  height: 700px;
  padding-top: 70px;
  margin: auto;
}

.item {
  padding: 5px;
}

.item img {
  height: 200px;
  margin: 10px;
  display: block;
}

.item span {
  display: block;
  padding: 5px;
  font-weight: bold;
  text-align: center;
}

```

https://github.com/benfin28/prj-rev-bwfs-tea-cozy/blob/ac59b98a5b67bdb79e63a9123a0a7af7fe5bbd60/Tea_Cosy/Resources/style.css#L88-L201
